name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk python3-pip unzip curl

    - name: Setup Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        rm cmdline-tools.zip
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

    - name: Setup PATH
      run: echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Accept licenses
      run: yes | sdkmanager --licenses

    - name: Install SDK packages
      run: sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Install Buildozer and dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip install buildozer cython

    - name: Build APK debug
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
