name: Build Kivy APK (Updated 2025)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-24.04

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

   jobs:
  build_apk:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install essential system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            openjdk-11-jdk-headless git zip unzip python3-pip \
            libncurses6 libncurses-dev libffi-dev libssl-dev libsqlite3-dev build-essential \
            liblzma-dev libbz2-dev libreadline-dev xz-utils tk-dev \
            libxml2-dev libxmlsec1-dev libjpeg-dev zlib1g-dev \
            autoconf automake libtool pkg-config curl

      - name: Download and install Android SDK Command-line tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          rm cmdline-tools.zip
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

      - name: Update PATH environment variable
        run: echo "PATH=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept all Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: Upgrade pip and install Buildozer latest
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install --upgrade buildozer

      - name: Build APK using Buildozer
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk

