name: Build and Release APK

on:
  push:
    branches:
      - main

jobs:
  build_release:
    runs-on: ubuntu-latest

    env:
      ANDROIDSDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ env.PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java and SDK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk git zip unzip python3-pip

      - name: Install Android SDK Command line tools
        run: |
          mkdir -p $ANDROIDSDK_ROOT/cmdline-tools
          cd $ANDROIDSDK_ROOT/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest

      - name: Set Android SDK path
        run: echo "PATH=${ANDROIDSDK_ROOT}/cmdline-tools/latest/bin:${ANDROIDSDK_ROOT}/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Upgrade pip and install buildozer
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install buildozer

      - name: Build APK debug
        run: buildozer android debug

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ github.run_number }}"
          name: "APK Build ${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
