name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build_apk:
    runs-on: ubuntu-22.04

    env:
      ANDROIDSDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ env.PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk git zip unzip python3-pip curl build-essential

      - name: Install Android SDK command line tools
        run: |
          mkdir -p $ANDROIDSDK_ROOT/cmdline-tools
          cd $ANDROIDSDK_ROOT/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest

      - name: Setup Android SDK PATH
        run: echo "PATH=${ANDROIDSDK_ROOT}/cmdline-tools/latest/bin:${ANDROIDSDK_ROOT}/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Upgrade pip and install Buildozer & Cython
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython

      - name: Build APK debug
        run: buildozer android debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: bin/*.apk
