steps:
  # 1. Checkout code
  - name: Checkout code
    uses: actions/checkout@v3

  # 4. Post Checkout Code - ví dụ liệt kê file, kiểm tra môi trường sau checkout
  - name: Post Checkout Code - List files
    if: always()
    run: ls -la

  # 2. Setup Python (ví dụ)
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.12'

  # 3. Post Setup Python - ví dụ kiểm tra python version ngay sau setup
  - name: Post Setup - Check Python version
    if: always()
    run: python --version

  # 5. Build APK
  - name: Build APK
    env:
      PATH: ${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin:${{ env.ANDROID_SDK_ROOT }}/platform-tools:${{ env.ANDROID_SDK_ROOT }}/build-tools/33.0.2:$PATH
    run: buildozer android debug

  # 6. Upload APK Artifact
  - name: Upload APK artifact
    uses: actions/upload-artifact@v4
    with:
      name: android-apk
      path: ./.buildozer/android/platform/build/dists/**/bin/*.apk
