name: Build APK with Buildozer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-setuptools \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          build-essential \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev
        pip3 install --upgrade cython
        pip3 install buildozer

    - name: Initialize Buildozer
      run: buildozer init

    - name: Modify buildozer.spec (if needed)
      run: |
        sed -i 's/package.name = .*$/package.name = myapp/' buildozer.spec
        sed -i 's/package.domain = .*$/package.domain = org.test/' buildozer.spec
        sed -i 's/requirements = .*$/requirements = python3,kivy/' buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp-apk
        path: bin/*.apk
